
import './globals.css'
import { AuthContextProvider } from '@/context/authContext'
import { DarkModeContextProvider } from '@/context/darkModeContext'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        <DarkModeContextProvider>
          <AuthContextProvider>
            {children}
          </AuthContextProvider>
        </DarkModeContextProvider>
      </body>
    </html>
  )
}
